### ISSUE TITLE
Problems in transformer

### ISSUE THREAD

**Issue by hewh16** [chan8972/Spike-FlowNet#1]
Hi~, When I was trying to run the main_spike_flow_dt1.py and main_spike_flow_dt4.py
There is a problem.

```
Traceback (most recent call last):
  File "main_spike_flow_dt1.py", line 550, in <module>
    main()
  File "main_spike_flow_dt1.py", line 526, in main
    train_loss = train(train_loader, model, optimizer, epoch, train_writer)
  File "main_spike_flow_dt1.py", line 253, in train
    for ww, data in enumerate(train_loader, 0):
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "main_spike_flow_dt1.py", line 148, in __getitem__
    aaa[:, :, p] = self.transform(aa[:, :, p])
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 49, in __call__
    img = t(img)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 110, in __call__
    return F.to_pil_image(pic, self.mode)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.0.0/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 115, in to_pil_image
    if npimg.shape[2] == 1:
IndexError: tuple index out of range
```

How should I fix it? Thanks :)

**Comment by chan8972** [comment]
Thank you for your interest. I suggest you to check your Pytorch version. It seems that you are using Pytorch 1.0.0, but our codes are only working based on Pytorch 1.1.0 version. For more information about the versions of all packages, please look at "https://github.com/chan8972/Spike-FlowNet/blob/master/environment.yml".

**Comment by hewh16** [comment]
Hi~ I have already change the Pytorch to the version required, but the problem still exists.

**Comment by chan8972** [comment]
On our side, it works fine. Did you follow our installation guidelines? Can you please follow our installation process creating anaconda3 environments, and let us know if it works for you? Thanks.
